T_ch2_Zjrua
CN-missemi/CN_missemi pull request #25
Opened 2021-02-25 03:42 UTC by GNAQ

2021-02-25 03:46 UTC, GNAQ commented
第 966 行的 [然后，这些是 Vim 的编辑器](https://github.com/CN-missemi/CN_missemi/blob/0f9e16fa031279bb971cbe830d89cacb52659b6d/ch2/%5B966-1265%5DCHN.txt#L1)

这里 Modifier 译为编辑器似乎不合适，但我也不明白应该如何处理。

2021-02-25 04:35 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +【966】 然后，这些是 Vim 的编辑器
```suggestion
【966】 那么，这些是 Vim 的修饰符
```
cc @GNAQ / https://github.com/CN-missemi/CN_missemi/pull/25#issuecomment-785555335

2021-03-01 14:21 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +并且这将会使我们发现这个工具能多快
```suggestion
这能让我们体会到这个工具的快
```

2021-03-01 14:21 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +大写 G 把文件拖到底
```suggestion
大写 G 把光标跳到文件底
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +【1117】 会立即把你扔到 insert mode 里
```suggestion
【1117】 会立即把你切到 insert mode 里 
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +在这举个例子，如果我想删掉这个 main
```suggestion
在这举个例子，如果我想删掉这个 `main` 
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +但是如果我随便再敲个字符，比如 j
```suggestion
但是如果我随便再敲个字符，比如 `j` 
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> + Vim 是通过硬盘上一个叫 vimrc 的文件配置的
```suggestion
Vim 是通过硬盘上一个叫 `vimrc` 的文件配置的
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +因此我们高度定制了 vimrc
```suggestion
因此我们高度定制了 `vimrc` 
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +就像成千上万的人们在 github 上分享他们自己的 vimrc
```suggestion
就像成千上万的人们在 GitHub 上分享他们自己的 `vimrc` 
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +或者是像 Jupiter notebook 一样
```suggestion
或者是像 Jupiter Notebook 一样
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +如果别的地方没有，你还可以谷歌一下
```suggestion
如果别的地方没有，你还可以搜一下
```
🌚

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +顺便提一下，明天的课换成了 data wrangling
```suggestion
顺便提一下，明天的课换成了数据整理
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +【1266】 确保所有人别上错课
```suggestion
【1266】 你们别上错课了
```

2021-03-03 02:33 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +现在周四和周二的课换了一下
```suggestion
现在把周四和周二的课换了一下
```

2021-03-05 18:48 UTC, GNAQ commented
review on translation mistakes has done.

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +【1072】还免于重复地输入相同的内容
```suggestion
在 Vim 中，按下 `.` 会重复之前的编辑命令

要想完成重复性工作

这是个好东西

【1072】还不用重复地输入相同内容
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +#￥%……&*（ #REVIEW
```suggestion
*重复最后一次操作那个的命令是啥键来着？*
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +因为它只会占用你像是几秒钟
```suggestion
因为它不会花多少时间
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +然后外边的是  #REVIEW （GNAQ-我也没听明白)
```suggestion
然后外边套了个 tmux
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +像这样把 Vim 放在左边，Shell 放在右边
```suggestion
我这里把 Vim 放在左边，Shell 放在右边
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +【1104】比如怎么在 Vim window 之间切换
```suggestion
【1104】比如怎么在 Vim 的 window 之间切换
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +至少一个，会让你对这工具有更深的理解 # REVIEW （GNAQ：我还是也是没听清）
```suggestion
首先会让你对这工具有更深的理解 # REVIEW （GNAQ：我还是也是没听清）
```

他说的就是这样做让你熟悉 Vim；又把 Vim 的优点带过去

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +如果别的地方没有，你还可以搜一下 # REVIEW 这里他说的又是啥？听不明白
```suggestion
如果上面没写的话你还可以搜一下 # REVIEW 这里他说的又是啥？听不明白
```
if its not in list

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +还有很多程序可以开启 Vim 模式 # REVIEW 原文真的是 Readline??
```suggestion
还有很多程序可以开启 Vim 模式 # REVIEW 原文真的是 Readline?? （1231-1232）
```

2021-03-06 01:25 UTC, ksyx commented on ch2/[966-1265]CHN.txt
> +所以我建议在你们空闲时间玩 #REVIEW （GNAQ：我也没听明白）
```suggestion
所以我建议你们有空再玩[*]
[*]别用来上课摸鱼
```

2021-03-06 03:47 UTC, CoelacanthusHex requested changes

2021-03-06 03:47 UTC, CoelacanthusHex commented on ch2/[966-1265]CHN.txt
> +还有很多程序可以开启 Vim 模式 # REVIEW 原文真的是 Readline??
```suggestion
还有很多基于 GNU Readline 的软件可以开启 Vim 模式，比如 Jupyter Notebook
```

2021-03-06 04:59 UTC, ksyx submitted a review, later dismissed
thx. lgtm

2021-03-06 05:25 UTC, merged