feat(ch5): translate 1-365
CN-missemi/CN_missemi pull request #53
Opened 2022-02-22 16:24 UTC by Officeyutong

2022-02-23 07:30 UTC, Officeyutong commented
已知问题：
- 用了很多中文双引号
- 所有出现的`git`都用了高亮
- 副字幕没有单独开一行，而是写在了主字幕内并单独标注
- 没有打标记提示点，严格对齐了英文行号

2022-02-23 12:38 UTC, ksyx commented
严格对齐英文行号也太强了

2022-02-23 13:58 UTC, ksyx reviewed
thx

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +如果你之前用过`git`、`subversion`、`mercurial`
```suggestion
如果你之前用过 `git`、`subversion`、`mercurial`
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +但我们先来概述一下
```suggestion
但我们先大概讲一下
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +的修改的工具
```suggestion
跟踪源代码、文件、文件夹修改的工具
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +和一群人一起开发软件这种事是很有用的
```suggestion
所以它们在一群人一起开发软件时
非常有用
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +提供弄清楚
```suggestion
这个是为了给我们弄清楚
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +这些问题的可能性
```suggestion
```
or
```suggestion
等等问题
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +这就是为什么版本控制系统很有用
```suggestion
这就是为什么版本控制系统用处很大
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +也很有用
```suggestion
就算你自己一个人做项目的时候
它也很有用
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +独立地写其他新特性
```suggestion
或者一边修 bug
一边独立地写其他新特性
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +写大型软件项目之外
```suggestion
除了做研究时和写大型软件项目的时候用
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +#REVIEW[整洁？] 此外它还有个比较整洁的功能
```suggestion
此外它还有个比较香的功能
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +里的某行代码
```suggestion
或者谁改了某个软件项目里的某行代码
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +以及这行代码是什么时候由谁改的
```
suggestion
以及这行代码是什么时候由谁改的
* 哈哈 原来是自己改的
```
（x

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +#REVIRE[衔接没太搞懂] 考虑假设你有个已经
```suggestion
好 现在我们假设你有个已经
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +然后它就可以去二分查找[*](一种算法，用以在有序列表里快速定位元素)代码历史
```suggestion
然后它就可以去二分查找[*](一种算法，用以在单调列表里快速定位元素)代码历史
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +功能
```suggestion
你就能发现很多又强又炫酷的功能
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +一共有很多版本控制系统
```suggestion
事实上市面上有很多版本控制系统
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +#REVIEW[这句我看不懂]
梗吧（
如果你说魔法的话

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +关联的
```suggestion
以及它们之间是怎么关联的
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +#REVIEW[奇怪的语义] 因为你最终要学很多不同的命令
```suggestion
因为实际上你要学很多不同的命令
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +有你们两个人写的东西的代码
```suggestion
然后你的程序里
有同时有了你们两个人写的代码
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +`git` 用了个术语 `树(tree)` 来表示
```suggestion
`git` 用了个术语树（tree）来表示
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +`git` 有一个用`有向无环图`[*]（`Directed Acylic Graph` ，一种图论数据结构）
```suggestion
`git` 有一个用有向无环图
[*]（Directed Acylic Graph，一种图论数据结构）
```

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +#REVIEW[迷惑] 然后我们想知道
迷惑在哪

2022-02-23 13:58 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +序列形式的一串快照来说
```suggestion
相比于线性的一串快照来说
```

2022-02-23 14:39 UTC, CoelacanthusHex commented on ch5/[1-365]CHN.txt
> +如果你之前用过`git`、`subversion`、`mercurial`
```suggestion
如果你之前用过 Git、Subversion、Mercurial
```
此处应该是指工具本身而不是 cli,不等宽且首字母大写

2022-02-23 14:39 UTC, CoelacanthusHex commented on ch5/[1-365]CHN.txt
> +这些问题的可能性
我认为
```suggestion
这些问题的可能
```
更好，「提供弄清XX问题的可能」

2022-02-23 14:39 UTC, CoelacanthusHex commented on ch5/[1-365]CHN.txt
> +图论[*](研究图的理论)里面的树型模型
```suggestion
图论[*](研究图的理论)里面的树型模型[*](此处应当是指的 Merkle Tree, Git 基于这种数据结构设计，尽管 Git 使用的版本应当被称为 Merkle DAG)
```

2022-02-23 14:39 UTC, CoelacanthusHex commented on ch5/[1-365]CHN.txt
> +“不知道，就记住这些 `shell` 命令
```suggestion
“不知道，就记住这些 Shell 命令
```
作为单独的名词而不是命令

2022-02-23 14:40 UTC, CoelacanthusHex commented
呜呜呜，ksyx 太强了，我都没东西可 review 了

2022-02-23 14:45 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +提供弄清楚
不对齐行号的话要不要额外标一下提示点啊
![UVA(S$5Y``1(1D{NL3GA{06](https://user-images.githubusercontent.com/9004058/155342405-59fdbde0-df1b-4ee8-bd12-0abaa80fe986.png)

2022-02-23 14:46 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +提供弄清楚
下次一定（

2022-02-23 14:46 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +有你们两个人写的东西的代码
“有同时有了”...?

2022-02-23 14:47 UTC, Officeyutong commented
> 

我太菜了 刚学会

2022-02-23 14:56 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +#REVIEW[迷惑] 然后我们想知道
我没看懂这句英文原文

2022-02-23 14:56 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +#REVIEW[这句我看不懂]
这个原文是啥啊 
![UVA(S$5Y``1(1D{NL3GA{06](https://user-images.githubusercontent.com/9004058/155344628-9f94bde6-baad-4d06-8108-55e285d18b65.png)

2022-02-24 16:37 UTC, kernelbin requested changes

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +我们对一组文件做出的更改
```suggestion
我们对一组文件做出的变化历史
```
原文是“track the history of changes”，似乎把history漏了？qwq

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +所以它们在一群人一起开发软件时
```suggestion
所以它们在一群人一起开发软件项目时
```

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +来追踪对一个文件夹或它的内容的更改
```suggestion
来追踪对一个文件夹和它的内容的变更
```
原文是“folder and its contents”

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +这些问题的可能
```suggestion
这个是为了让我们可以弄清楚
“某个文件的某个修改是谁写的”
“某个更改是什么时候做的”
这一类问题
```

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +这就是为什么版本控制系统用处很大
原文是“so why is version control useful”，是个反问句吧qwq
然后接下来的well... 是在回答？

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +一边独立地写其他新特性
这里我觉得翻译的怪怪的 但我也不知道怎么改进好qaq
HELP NEEDED

tips: 原文是“be able to work on bug fixes while keeping work on different features independent”

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +是一个非常有价值的工具
```suggestion
是一个极有价值的工具
```

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +这些小型的东西上也用 `git`
唔，我说实话也不知道怎么翻译合适，但我觉得顺序不必颠倒？或许可以用“更不用提”来连接两段
HELP NEEDED

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +来解决不同人在写同一块代码时
```suggestion
就比如想要通过发送代码补丁
来解决不同人在同时写同一块代码
```

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +此外版本控制系统还有一些
此外连着用了两次了 换一个？qwq

2022-02-24 16:37 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +但是你并不知道什么时候改的代码让它挂了
```suggestion
但是你并不确切的知道什么时候代码“退化”了
```

2022-02-24 22:46 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +一边独立地写其他新特性
把修 bug 和开发新功能分开
互不影响

这样？

2022-02-25 04:10 UTC, GNAQ commented on ch5/[1-365]CHN.txt
> +只要你对这个东西好奇
不太自然

2022-02-25 05:33 UTC, GNAQ commented
OK，我最后校一遍就可以了

目前 ~154L

2022-02-25 10:50 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +然后删掉项目，再下一份新的”
需不需要为每一句都两侧加上双引号啊qwq

2022-02-25 10:50 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +把它们打到终端里来跑
原文是“type them to sync up”，是不是翻译成「把他们打到终端里来同步」比较准确啊qwq

2022-02-25 10:50 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +它是个全是坑的抽象
```suggestion
`git` 的接口设计地非常糟糕

它的抽象漏洞百出
```

2022-02-25 10:50 UTC, kernelbin commented on ch5/[1-365]CHN.txt
> +并不那么复杂的数据模型
```suggestion
并且一旦你理解了 `git` 的内部那些

没那么复杂的数据模型
```

2022-02-25 11:52 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +并不那么复杂的数据模型
并没有那么复杂？

2022-02-25 14:20 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +把它们打到终端里来跑
`sync up` 不就是跑那些指令能搞出来的效果吗，你写个同步反而让人摸不着头脑

2022-02-25 14:21 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +把它们打到终端里来跑
跑 => 协作？

2022-02-25 14:23 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +然后删掉项目，再下一份新的”
你看看原神那些角色突破材料的元素块的多行引用是咋搞的，我觉得应该可以每行开头加左半引号，最后一行末尾加右半引号

2022-02-26 07:42 UTC, Officeyutong commented on ch5/[1-365]CHN.txt
> +把它们打到终端里来跑
> 跑 => 协作？

好，以ksyx教授的为准

2022-03-03 05:20 UTC, GNAQ commented on ch5/[1-365]CHN.txt
> +然后删掉项目，再下一份新的”
这是符合中国排版规范的

2022-03-03 05:23 UTC, GNAQ commented on ch5/[1-365]CHN.txt
> +它是个全是坑的抽象
我觉得此处「漏洞」不佳（虽然英文原文想表达这一意思），它适于形容某设计出现了遗漏或者不完善，我觉得拿来形容 git 不太合适

2022-03-03 05:25 UTC, GNAQ approved these changes, later dismissed

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +所以在我们实际开始之前，一条小贴士
```suggestion
所以在我们实际开始之前稍微说一下
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +只要你对这个东西好奇
```suggestion
只要你对这个东西好奇 就都可以问
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +之前用没用过版本控制系统
```suggestion
之前有哪些人

用过版本控制系统
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +所以它们在一群人一起开发软件项目时
```suggestion
所以它在一群人一起开发软件项目时
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +或者干一些类似的事
```suggestion
你也可以给这些快照附加其他你想要的额外信息
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +之类的元数据
```suggestion
像是作者、提交时间戳之类的元数据
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +用合适的方法复制下来
```suggestion
用某种方法复制下来
```

2022-03-03 20:29 UTC, ksyx commented on ch5/[1-365]CHN.txt
> +* ？？？这真的可能吗？？？
refactor 感觉有可能（

或者是这个 bug 影响实现新 feature 了

2022-03-12 14:26 UTC, merged